// This file will be auto-generated by Supabase CLI
// For now, we'll define basic types manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          full_name: string | null
          avatar_url: string | null
          interests: string[]
          preferred_level: 'Beginner' | 'Intermediate' | 'Advanced' | null
          role: 'member' | 'admin'
          created_at: string
        }
        Insert: {
          id: string
          full_name?: string | null
          avatar_url?: string | null
          interests?: string[]
          preferred_level?: 'Beginner' | 'Intermediate' | 'Advanced' | null
          role?: 'member' | 'admin'
          created_at?: string
        }
        Update: {
          id?: string
          full_name?: string | null
          avatar_url?: string | null
          interests?: string[]
          preferred_level?: 'Beginner' | 'Intermediate' | 'Advanced' | null
          role?: 'member' | 'admin'
          created_at?: string
        }
      }
      subscriptions: {
        Row: {
          id: string
          user_id: string
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          status: string | null
          price_id: string | null
          current_period_end: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          status?: string | null
          price_id?: string | null
          current_period_end?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          status?: string | null
          price_id?: string | null
          current_period_end?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      styles: {
        Row: {
          id: string
          name: string
          slug: string
          position: number
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          position?: number
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          position?: number
          created_at?: string
        }
      }
      levels: {
        Row: {
          id: string
          name: string
          position: number
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          position?: number
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          position?: number
          created_at?: string
        }
      }
      videos: {
        Row: {
          id: string
          title: string
          slug: string
          description: string | null
          duration_seconds: number | null
          teacher: string | null
          published: boolean
          video_path: string | null
          preview_path: string | null
          thumbnail_path: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          slug: string
          description?: string | null
          duration_seconds?: number | null
          teacher?: string | null
          published?: boolean
          video_path?: string | null
          preview_path?: string | null
          thumbnail_path?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          slug?: string
          description?: string | null
          duration_seconds?: number | null
          teacher?: string | null
          published?: boolean
          video_path?: string | null
          preview_path?: string | null
          thumbnail_path?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      video_styles: {
        Row: {
          video_id: string
          style_id: string
        }
        Insert: {
          video_id: string
          style_id: string
        }
        Update: {
          video_id?: string
          style_id?: string
        }
      }
      video_levels: {
        Row: {
          video_id: string
          level_id: string
        }
        Insert: {
          video_id: string
          level_id: string
        }
        Update: {
          video_id?: string
          level_id?: string
        }
      }
      video_views: {
        Row: {
          id: number
          video_id: string
          user_id: string | null
          viewed_at: string
        }
        Insert: {
          id?: number
          video_id: string
          user_id?: string | null
          viewed_at?: string
        }
        Update: {
          id?: number
          video_id?: string
          user_id?: string | null
          viewed_at?: string
        }
      }
    }
  }
}

